# A Simple Neural Network

It is easy to create a single-layer neural network using pytorch.

The outputs of the neural network are merely linear combinations of the inputs.


In [1]:
import torch

inputs = torch.Tensor([[1, 2]])
print("The inputs are:")
print(inputs)


The inputs are:
tensor([[ 1.,  2.]])


We've used horizontal matrices for the input and output vectors (matrices with 1 row).

So, you have to multiply the inputs by the weights using $inputs * weights$ instead of $weights * inputs$.

In [2]:
weights = torch.Tensor([[3, 7],[4, 1]])
print("The weights are:")
print(weights)

bias = torch.Tensor([[0.5, 0.3]])
print("The biases are:")
print(bias)


The weights are:
tensor([[ 3.,  7.],
        [ 4.,  1.]])
The biases are:
tensor([[ 0.5000,  0.3000]])


The if the input is $f$ and the output is $c$, then $c = f*W + b$

In [3]:
outputs = inputs.mm(weights) + bias
print("The outputs are:")
print(outputs)

The outputs are:
tensor([[ 11.5000,   9.3000]])


## Exercise

Modify the above program to create a neural network with inputs $\begin{bmatrix}1 & 2 & 3\end{bmatrix}$ weights $\begin{bmatrix}3 & 7\\4 & 1\\1 & 2\end{bmatrix}$ and biases $\begin{bmatrix}0.5 & 0.3\end{bmatrix}$ and compute the output.