# A Simple Neural Network Classifier

It is easy to create a single-layer neural network using pytorch.

The outputs of the neural network are merely linear combinations of the inputs.

We have already seen how to do that in Exercise 210.

You can turn the neural network's outputs into a decision about a category by treating each output as the neural network's *preference for a category*.

The favoured category is the one represented by the output with the highest value.

For example, if the outputs are $\begin{bmatrix}11 & 12 & 13\end{bmatrix}$ and they represent three classes $(0, 1, 2)$, the class chosen by the neural network is class $2$.

In [1]:
import torch

data = torch.Tensor([[2, 3]])
print(data)

weights = torch.Tensor([[0, 6],[0, 9]])
print(weights)

result = torch.mm(data, weights)
print(result)

maxv, maxi = torch.max(result, 1)
print("Selected category = "+str(maxi[0]))

tensor([[ 2.,  3.]])
tensor([[ 0.,  6.],
        [ 0.,  9.]])
tensor([[  0.,  39.]])
Selected category = tensor(1)


## Exercise

You'll see that this classifier consistently picks category 1, for all positive inputs, no matter what those inputs are.

Can you come up with a classifier that always picks category 0?