# Tensors in Pytorch

Tensors are just a generalization of vectors and matrices.  Vectors are ordered arrangements of data in 1 dimension.  Matrices are ordered arrangements of data in 2 dimensions.  If you generalize ordered arrangements of data in space to any number of dimensions, you get tensors.  Vectors and matrices are also tensors.

Tensors are a very useful tool for neural networks because neural networks and their data processing pipelines can be built entirely out of tensors.

The data that is fed to neural networks can be represented by tensors.  The parameters of the neural networks (the weights and the biases) can be represented by tensors.  So can the outputs.

So, once you get the hang of tensors, you can start wiring up neural networks in no time at all.

This set of exercises shows you how to create and manipulate tensors in Pytorch.

Let's start by importing Pytorch.

In [1]:
import torch

## Construction of Tensors

First, let's create a 1-dimensional tensor (just a fancy name for a vector) with 2 elements!

The constructor takes one parameter for each dimension of the tensor, specifying the tensor's length in that dimension.

This being a 1-dimensional tensor, its constructor needs just one parameter, specifying the length of the vector.

In [2]:
a1DTensor = torch.Tensor(2)
a1DTensor

tensor([ 0., -2.])

The vector, as you can see, is uninitialized (well, initialized with garbage).  If you'd rather have it filled with zeros, you can do the following instead. 

In [3]:
a1DTensor = torch.zeros(2)
a1DTensor

tensor([ 0.,  0.])

If you want to initialize a tensor with more than one dimension, pass more parameters to the constructor or factory method.

Other common factory methods are 'ones' and 'rand' and 'randn'.

We create a 2-dimensional tensor filled with ones, a 3-dimensional tensor filled with random numbers between 0 and 1, and a 4-dimensional tensor filled with random numbers with a normal distribution with a mean at zero and a variance of 1.

In [4]:
a2DTensor = torch.ones(2, 3)
a2DTensor

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

So you can create tensors of arbitary dimensions.

The 2-dimensional tensors, as you know, are called matrics.

Tensors are merely generalization of vectors and matrices to higher dimensions.

You can also create tensors from matrices.  This is particularly useful when you're converting input data and output data into tensors.

In [5]:
a2DTensor = torch.Tensor([[1, 2, 3],[4, 5, 6]])
a2DTensor

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

## Visualizing Tensors

In [6]:
a3DTensor = torch.rand(2, 3, 4)
a3DTensor

tensor([[[ 0.9006,  0.0140,  0.5068,  0.1320],
         [ 0.4104,  0.6199,  0.3985,  0.8844],
         [ 0.2050,  0.1709,  0.3295,  0.8669]],

        [[ 0.9818,  0.0751,  0.0092,  0.2305],
         [ 0.4660,  0.5046,  0.1751,  0.7514],
         [ 0.6547,  0.5198,  0.5565,  0.4588]]])

Note that when Pytorch prints a tensor, the outermost square brackets enclose the first dimension.

The next inner nesting of square brackets enclose the second dimension (here, the matrix-row dimension).

The innermost square brackets point in the third dimension (here, the matrix-column dimension).

In the Pytorch representation, the last two dimensions are represented as matrix-row and matrix-column.  This out-in ordering of dimensions is good to get a hang of for debugging data flows.

In [7]:
a4DTensor = torch.randn(2, 3, 4, 5)
a4DTensor

tensor([[[[-1.1389,  0.2702, -1.4285, -0.9025, -1.0754],
          [-0.1063, -0.0091,  1.2139, -0.3160,  1.6785],
          [ 0.9278,  1.7833, -0.3822, -1.5971,  0.4693],
          [-0.2132, -0.0054,  1.7708,  0.7218,  0.2263]],

         [[ 0.1724,  0.2538,  0.3255,  0.3690,  1.0615],
          [-0.9741, -0.5404, -0.4065,  0.2456,  1.5072],
          [-0.8681, -0.3479, -0.2729, -0.5055, -1.1438],
          [-0.5925,  0.4438,  1.4026, -1.3871, -0.2138]],

         [[-0.4431, -0.6146,  0.2168, -0.8108, -1.0003],
          [ 0.1847, -0.9210,  1.1536, -0.2260,  0.1937],
          [-0.6403, -1.5614, -0.5467,  0.9163,  0.4388],
          [-0.0931,  2.0600, -1.6304,  0.0111,  0.5999]]],


        [[[ 0.1407,  0.3031, -0.0901, -0.4847, -0.7330],
          [-0.7387,  1.2340,  0.9686, -2.0939,  1.5344],
          [-0.3066,  0.1749, -0.5112,  1.4151,  0.3104],
          [-0.4935, -0.1328,  0.3981, -0.5200, -1.6364]],

         [[-0.6043,  0.6915, -0.3539, -0.0924, -1.5290],
          [ 0.4126,  

## Editing Tensors

You can slice and dice tensors.

The following code assigns the value 4 to all elements in the second column of the 2D tensor.

In [8]:
a2DTensor[:,1] = 4
a2DTensor

tensor([[ 1.,  4.,  3.],
        [ 4.,  4.,  6.]])

You can also edit individual elements in the tensor.

In [9]:
a2DTensor[0,1] = 2
a2DTensor[1,1] = 5
a2DTensor

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

You can fill the tensor with the value 2.2 (any member function ending in an underscore modifies the object it was called on).

In [10]:
a2DTensor.fill_(2.2)
a2DTensor

tensor([[ 2.2000,  2.2000,  2.2000],
        [ 2.2000,  2.2000,  2.2000]])

You can slice the matrix and return the second row as follows:

In [11]:
a2DTensor[1]

tensor([ 2.2000,  2.2000,  2.2000])

Or the first column (the indices start at 0):

In [12]:
a2DTensor[:,0]

tensor([ 2.2000,  2.2000])

You can also get back the dimensions of a tensor using the size() method.

In [13]:
a2DTensor.size()

torch.Size([2, 3])

Or a specific dimension (and this returns an integer):

In [14]:
a2DTensor.size(0)

2

There you go.  If you have a 1D tensor, and look up an element in it, you get a float or an int.  Similarly if you have e 2D tensor and look up an element at a row and column, you get a float or an int.

In [15]:
a1DTensor[0]

tensor(0.)

In [16]:
a2DTensor[0,0]

tensor(2.2000)

The tensors are by default assumed to be meant to hold real numbers.

You can also explicitly specify in the constructor whether the tensor should hold real numbers or be limited to integers.

The following will hold only integers.

In [17]:
anIntTensor = torch.IntTensor(1,2)
anIntTensor

tensor([[ 0.0000e+00, -1.0737e+09]], dtype=torch.int32)

It appears to hold floating point values because it hasn't been initialized.

Fill it with something.


In [18]:
anIntTensor.fill_(5)
anIntTensor

tensor([[ 5,  5]], dtype=torch.int32)

The following tensor is intended to hold real numbers.

In [19]:
aFloatTensor = torch.FloatTensor(1,2)
aFloatTensor

tensor([[ 0., -2.]])

Unlike an int tensor, you can can fill a float tensor with real numbers.

In [20]:
aFloatTensor.fill_(5.5)
aFloatTensor

tensor([[ 5.5000,  5.5000]])

## Exercise:  Operations on Tensors

Create and add two tensors.  This tutorial on Pytorch explains how: http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#operations